config/routes.rb
SvbfSite::Application.routes.draw do

  resource :calendar, only: [:show], controller: :calendar

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions
  
  get "home/index"

  root 'home#index'

  resources :events

end

app/models/event.rb
class Event < ActiveRecord::Base

  before_validation :format_params

  validates :title, presence: true
  validates :description, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  
  private 
	  def format_params 
	  	self.start_time = start_time.to_formatted_s(:db)
	  	self.end_time = end_time.to_formatted_s(:db)
	  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  after_save :clear_password
  
  validates :password, :confirmation => true
  validates_length_of :password, :in => 6..20, :on => :create
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, :uniqueness => true, format: { with: VALID_EMAIL_REGEX }
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt) && (email == "pramods@umich.edu" || email == "seethavr@yahoo.com" || email == "nvramu@yahoo.com")
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def clear_password
    self.password = nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue ActiveRecord::RecordNotFound
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def new
		@event = Event.new
	end

	def create
		@event = Event.new(event_params)

		if @event.save
			redirect_to action: "index"
		else 
			render :action => 'new'
		end
	end

	def index
		@events = Event.all.order('created_at DESC')
	end

	def show
	  @event = Event.find(params[:id])
	end

	def destroy
		@event = Event.find(params[:id])
		@event.destroy
		redirect_to action: "index"
		flash[:error] = "Event was deleted!"
	end
 
  private
	def event_params
		params.require(:event).permit(:title, :description, :start_time, :end_time)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @events_by_date = Event.group(@date.wday)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
	  user = User.authenticate(params[:email], params[:password])
	  if user
	    session[:user_id] = user.id
	    redirect_to root_url, :notice => "Logged in!"
	  else
	    flash.now.alert = "Invalid email or password"
	    render "new"
	  end
	end

	def destroy
	  session[:user_id] = nil
	  redirect_to root_url, :notice => "Logged out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
	  @user = User.new
	end

	def create
	  @user = User.new(user_params)
	  if @user.save
	    redirect_to root_url, :notice => "Signed up!"
	  else
	    render "new"
	  end
	end

  private
	  def user_params
    	params.require(:user).permit(:username, :email, :password, :salt, :encrypted_password)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calendar/show.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <div class="well controls">
      <%= link_to calendar_path(date: @date - 1.month), class: "btn btn-default" do %>
        <i class="glyphicon glyphicon-backward"></i>
      <% end %>
      <%= "#{@date.strftime("%B")} #{@date.year}" %>
      <%= link_to calendar_path(date: @date + 1.month), class: "btn btn-default" do %>
        <i class="glyphicon glyphicon-forward"></i>
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= calendar @date do |date| %>
	  <%= date.day %>
	  <% if @events_by_date[date] %>
	    <ul>
	      <% @events_by_date[date].each do |event| %>
	        <li><%= link_to event.name, event %></li>
	      <% end %>
	    </ul>
	  <% end %>
	<% end %>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_for @event, :class => "form-horizontal" do |f| %>

  <% if @event.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <strong><%= pluralize(@event.errors.count, "error") %> prohibited
        this event from being saved: </strong>
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Add Event</h3>
  </div>
  <div class="panel-body">
      <div class="form-group">
        <%= f.label :title %><br>
        <%= f.text_field :title, :class => "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :start_time, "Start Time" %><br>
        <div class='input-group date' id='datetimepicker8' data-date-format="YYYY-MM-DD HH:mm">
            <input type='text' class="form-control" id="event_start_time" name="event[start_time]"/>
            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :end_time, "End Time"  %><br>
        <div class='input-group date' id='datetimepicker9' data-date-format="YYYY-MM-DD HH:mm">
            <input type='text' class="form-control" id="event_end_time" name="event[end_time]" />
            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :description %><br>
        <%= f.text_area :description, :class => "form-control", :size =>"24x5" %>
      </div>
     
      <p>
        <%= f.submit :class => "submit" %>
      </p>

    <% end %>
  </div>
</div>

<script type="text/javascript">
    $(function () {
        $('#datetimepicker8').datetimepicker({
          minuteStepping:5
        });
        $('#datetimepicker9').datetimepicker({
          minuteStepping:5
        });
        $("#datetimepicker8").on("dp.change",function (e) {
           $('#datetimepicker9').data("DateTimePicker").setMinDate(e.date.to_time);
        });
        $("#datetimepicker9").on("dp.change",function (e) {
           $('#datetimepicker8').data("DateTimePicker").setMaxDate(e.date);
        });
    });
</script>

app/views/events/index.html.erb
<% if current_user %>
  <%= link_to 'Create New Event', new_event_path, :class => "btn btn-default" %>
<br/><br/>
<% end %>

<div id="calendar"></div>
<br/>

<% @events.each do |event| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4><%= event.title %></h4>
    </div>
    <div class="panel-body">
    <p><%= event.description %></p>
    <p id="time"><small><%= time_ago_in_words(event.created_at) %> ago</small></p>
    <% if current_user %>
      <%= link_to 'Destroy', {:controller=>:events,:action=>:destroy, :id=>event}, :method=>:delete %>
    <% end %>
    </div>
  </div>
<% end %>

app/views/events/new.html.erb
<div class="row">
  <div class="col-md-8">
    <%= render 'form' %>
  </div>
</div>

app/views/events/show.html.erb
<p><%= link_to 'Back', events_path, :class => "btn btn-default", :method => :get  %></p>

<div class="col-md-10">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4><%= @event.title %></h4>
    </div>
    <div class="panel-body">
    <p><%= @event.description %></p>
    <p id="time"><small><%= time_ago_in_words(@event.created_at) %> ago</small></p>
    <% if current_user %>
      <%= link_to 'Destroy', {:controller=>:events,:action=>:destroy, :id=>event}, :method=>:delete %>
    <% end %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
	<h1>Sringeri Vidhya Bharati Foundation</h1>
	<p>Farmington Hills, Michigan</p>
</div> 

<h1>Event Calendar</h1>
<div class="well" id='calendar'></div>

<script type='text/javascript'>
	$(document).ready(function() {
	  $("#calendar").fullCalendar(
	    events: '/events.json'
	  )
	});
</script>

app/views/layouts/_disclaimer.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Disclaimer</h4>
      </div>
      <div class="modal-body">
        The names and contact information on this Web site are published to facilitate contact with those listed for SVBF purposes only. It is not intended, and we request that they not be used, for any other purposes.<br><br>

        SVBF maintains this Web site to enhance public access to information on the organization’s activities. This is a service that is continually under development. We will make every effort to keep this site current and to correct errors brought to our attention. Care has been taken in the compilation of this web site. While every reasonable effort is made to ensure that the information provided on this site is accurate, no guarantees for the currency or accuracy of information are made. In no event will SVBF be liable for any loss, damage or inconvenience including, without limitation, indirect or consequential loss or damage, or any loss or damages whatsoever arising from use or loss of use of, data or profits arising out of or in connection with the use of SVBF’s website.<br><br>

        All programs listed in the site are subject to change without further notice<br>

        Parents are responsible for the children. SVBF is not responsible for any loss, damage or injuries on the temple premises.<br><br>

        Links to external, or third party Web sites, are provided solely for visitors’ convenience. Links taken to other sites are done so at your own risk and SVBF accepts no liability for any linked sites or their content. When you access an external Web site, keep in mind that SVBF has no control over its content.<br><br>

        Any link from SVBF to an external Web site does not imply or mean that SVBF endorses or accepts any responsibility for the content or the use of such Web site. SVBF does not give any representation regarding the quality, safety, suitability, or reliability of any external Web sites or any of the content or materials contained in them. It is important for users to take necessary precautions, especially to ensure appropriate safety from viruses, worms, Trojan horses and other potentially destructive items.<br><br>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">SVBF Michigan</a> 
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<ul class="nav navbar-nav">
	<li><%= link_to 'Events', events_path %></li>
	<li class="dropdown">
	  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Media <b class="caret"></b></a>
	  <ul class="dropdown-menu">
	    <li><%= link_to 'Photos', albums_path %></li>
	  </ul>
	</li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SVBF | MI" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Svbf Site" %>">
    <%= stylesheet_link_tag "http://yandex.st/bootstrap/3.0.2/css/bootstrap.min.css", media: "all" %>
    <%= stylesheet_link_tag "http://yandex.st/bootstrap/3.0.2/css/bootstrap-theme.min.css", media: "all" %>
    <%= javascript_include_tag "http://yandex.st/bootstrap/3.0.2/js/bootstrap.min.js" %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag "application-print", :media => "print" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <% if notice %>
        <div class="alert alert-info alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= notice %>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= alert %>
        </div>
      <% end %>
      <div class="alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong><i class="fa fa-bug fa-lg"></i> Warning!</strong> This website is currently under development. Report any bugs to the <strong><a href="mailto:sumedha.pramod@gmail.com">webmaster</a></strong>!
      </div>
      <div class="well">

        <div class="row">

          <div class="col-md-8 container">
            <%= yield %>
            <br>
          </div>

          <div class="col-md-4">
          
            <div class="panel panel-default">
              <div class="panel-body">

                <script src="assets/javascript/jquery.film_roll.js"></script>

                <div id="film_roll">
                  <div>
                    <%= image_tag('slider1.jpg', :class => 'img-rounded')  %>
                  </div>
                  <div>
                    <%= image_tag('slider2.jpg', :class => 'img-rounded')  %>
                  </div>
                  <div>
                    <%= image_tag('slider3.jpg', :class => 'img-rounded')  %>
                  </div>
                </div>

                <script>
                  $(document).ready(function(){
                    var film_roll = new FilmRoll({
                        configure_load: true,
                        container: '#film_roll',
                        interval: 2000
                      });
                  });
                </script>

              </div>
            </div>
            <br>

            <div class="panel panel-default">
              <div class="panel-heading"><center>Temple Information</center></div>
              <div class="panel-body">
              <p><center><div id="geolocation" style='width: 95%; height: 200px;'></div></center></p>
                <address>
                  26325 Halsted Rd<br>
                  Farmington Hills, MI 48331<br><br>
                  (248) 247-6699<br>
                  <a href="mailto:svbf.detroit@gmail.com">svbf.detroit@gmail.com</a>
                </address>
                <strong>Sri Lalita Sahasranama Parayanam</strong><br>
                Saturday - Thursday 7:00 - 7:30pm<br>
                <strong>Sri Lalita Sahasranama Namavali</strong><br>
                Friday 7:00 - 7:30pm<br>
              </div>
            </div>
          
            <div class="panel panel-default">
              <div class="panel-heading"><center>Other SVBF Locations</center></div>
              <div class="panel-body">
                <p><a href="http://www.svbfcanada.com/SVBF/">Toronto, Canada</a></p>
                <p><a href="http://svbf.org/">Stroudsburg, PA</a></p>
              </div>
            </div>

          </div>

        </div>        
        <br>

        <!-- ########################## FOOTER #############################-->
        <footer>
          <small><center>
            <% if current_user %>
              Logged in as <%= current_user.email %>.
              <%= link_to "Log out", log_out_path %>
            <% else %>
              <%= link_to "Sign up", sign_up_path %> or 
              <%= link_to "Log in", log_in_path %>
            <% end %>
          </center></small>

          <h5 class="text-center"><small>
          Sringeri Vidya Bharati Foundation, USA. All rights reserved &copy; 2014<br>
          May the Grace of Sharadamba and blessings of the Acharya be with you all!<br>
          Questions or Comments about this website? Email the <a href="mailto:sumedha.pramod@gmail.com">Web Master</a><br>
          <a href="#" data-toggle="modal" data-target="#myModal">Disclaimer</a> 
          <% render 'layouts/disclaimer' %>
          </small></h5>
        </footer>

      </div>
    </main>

    <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

    <script>
      $(document).ready(function(){
        var handler = Gmaps.build('Google');
        handler.buildMap({ internal: {id: 'geolocation'} }, function(){
        });

        function displayOnMap(position){
          var marker = handler.addMarker({
            lat: 42.485338,
            lng: -83.418008
          });
          handler.map.centerOn(marker);
          handler.getMap().setZoom(15);
        };  
      });
    </script>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>